// SEED FINAL 1+3 - Família Oliveira
export const contasIniciais = [
  {"id":"inc_thiago","type":"income","title":"Salário Thiago (média)","owner":"Thiago","value":5500},
  {"id":"inc_adriele","type":"income","title":"Salário Adriele (média)","owner":"Adriele","value":600},
  {"id":"fix_aluguel","type":"fixed","title":"Aluguel","owner":"Casa","value":1600},
  {"id":"fix_luz","type":"fixed","title":"Luz","owner":"Casa","value":278.96},
  {"id":"fix_agua","type":"fixed","title":"Água (última)","owner":"Casa","value":253.88,"date":"2025-11-12"},
  {"id":"fix_mercado","type":"variable","title":"Mercado","owner":"Casa","value":500},
  {"id":"fix_internet","type":"fixed","title":"Internet/Telefone","owner":"Casa","value":128.99},
  {"id":"fix_carro","type":"fixed","title":"Carro (parcela)","owner":"Thiago","value":767.32,"meta":"22/48"},
  {"id":"fix_nubank","type":"variable","title":"Cartão Nubank","owner":"Casa","value":232.78},
  {"id":"fix_ailos","type":"fixed","title":"Ailos (parcela)","owner":"Thiago","value":196.63},
  {"id":"fix_tim","type":"fixed","title":"Internet TIM móvel","owner":"Casa","value":48.99},
  {"id":"fix_sofa","type":"fixed","title":"Cartão Gabriel - Sofá","owner":"Gabriel","value":250},
  {"id":"var_lazer","type":"variable","title":"Lazer","owner":"Família","value":150},
  {"id":"var_farmacia","type":"variable","title":"Farmácia","owner":"Família","value":150},
  {"id":"var_gasolina","type":"variable","title":"Gasolina","owner":"Thiago","value":250},
  {"id":"var_jeitto","type":"variable","title":"Empréstimo Jeitto","owner":"Thiago","value":221.10},
  {"id":"var_w","type":"variable","title":"Empréstimo W","owner":"Thiago","value":300},
  {"id":"var_mei","type":"variable","title":"MEI - atrasado","owner":"Thiago","value":100},
  {"id":"debt_andrey","type":"goal","title":"Pagar dívida Andrey","owner":"Thiago","value":3000,"target":3000,"progress":0},
  {"id":"debt_gabriel","type":"goal","title":"Pagar dívida Gabriel","owner":"Thiago","value":2000,"target":2000,"progress":0},
  {"id":"meta_claro","type":"goal","title":"Limpar nome - Claro","owner":"Thiago","value":325.52,"target":325.52,"progress":0},
  {"id":"meta_shopee","type":"goal","title":"Limpar nome - Shopee","owner":"Thiago","value":173.59,"target":173.59,"progress":0},
  {"id":"meta_adriele","type":"goal","title":"Limpar nome - Adriele","owner":"Adriele","value":3000,"target":3000,"progress":0},
  {"id":"cofrinho_emergencia","type":"cofrinho","title":"Poupança Emergencial","owner":"Família","value":0,"target":10000,"progress":0},
  {"id":"cofrinho_13","type":"cofrinho","title":"13º do Thiago","owner":"Thiago","value":0,"target":5500,"progress":0},
  {"id":"manutencao_carro","type":"goal","title":"Manutenção preventiva - carro","owner":"Thiago","value":2300,"target":2300,"progress":0},
  {"id":"dpvat","type":"variable","title":"DPVAT","owner":"Thiago","value":94.61},
  {"id":"multa","type":"variable","title":"Multa + DPVAT","owner":"Thiago","value":232.50}
];
